<a href="https://colab.research.google.com/github/krshnapriy/Numpy_Practice/blob/main/Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY TUTORIAL PRACTICE**


In [2]:
import numpy as np
myPythonList = [1,9,8,3]
print(myPythonList)


[1, 9, 8, 3]


In [ ]:
numpy_array_from_list = np.array(myPythonList)
numpy_array_from_list

array([1, 9, 8, 3])

In [ ]:
a  = np.array([1,9,8,3])
print(a)

[1 9 8 3]


In [ ]:
x=numpy_array_from_list + 10
print(x)

[11 19 18 13]


In [ ]:
x=numpy_array_from_list * 2
print(x)

[ 2 18 16  6]


**Shape and Datatype of array**

In [ ]:
a  = np.array([1,2,3])
print(a.shape)
print(a.dtype)

(3,)
int64


In [ ]:
c = np.array([(1,2,3),
              (4,5,6)])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [ ]:
d = np.array([
    [[1, 2,3,4],
        [4, 5, 6,7]],
    [[7, 8,9,10],
        [10, 11, 12,13]]
])
print(d.shape)
print(d.dtype)

(2, 2, 4)
int64


**numpy.zeros() and numpy.ones() to create matrix full of zeros and ones respectively**

In [ ]:
x=np.zeros((3,3), dtype=np.int16)
print(x)

y=np.ones((1,3,4), dtype=np.int16)
print(y)	

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


**Reshaping the array and Flattening the array**

In [ ]:
e  = np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

**hstack to appened data horizontally and vstack to append data vertically**

In [3]:
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))
print('Vertical Append:', np.vstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]
Vertical Append: [[1 2 3]
 [4 5 6]]


**numpy.random.normal(loc, scale, size) to generate random numbers**

In [4]:
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[5.0464759  6.07534233 5.39785055 5.13877751 5.7293195  5.57728082
 5.61586418 4.34897646 4.51343169 4.69432309]


**asarray()function is used when you want to convert an input to an array.**

In [5]:
A = np.matrix(np.ones((4,4)))		
np.array(A)[2]=2 
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
np.asarray(A)[2]=2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


**numpy.arange()**

In [9]:
np.arange(1, 14, 4)	

array([ 1,  5,  9, 13])

**numpy.linspace(start, stop, num, endpoint) gives evenly spaced samples.**

In [10]:
np.linspace(1.0, 10.0, num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [11]:
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

**numpy.logspace(start, stop, num, endpoint) returns even spaced numbers on a log scale**

In [12]:
np.logspace(3.0, 4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

**Indexing and Slicing**

In [13]:
e  = np.array([(1,2,3), (4,5,6)])
print(e)

[[1 2 3]
 [4 5 6]]


In [15]:
print('First row:', e[0])
print('Second row:', e[1])

First row: [1 2 3]
Second row: [4 5 6]


In [19]:
print('Second column:', e[:,1])	
print('Second row, 2 values:',e[1, :2])

Second column: [2 5]
Second row, 2 values: [4 5]


**Function Numpy Min np.min(), Max np.max(), Mean np.mean(), Median np.median(), Standard deviation np.std()**

In [22]:
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)	

print('MIN:',np.min(normal_array))
print('MAX:',np.max(normal_array))
print('MEAN:',np.mean(normal_array))
print('MEDIAN:',np.median(normal_array))
print('STANDARD DEVIATION:',np.std(normal_array))

[4.99684435 5.44282596 4.45990478 4.8469191  4.07892839 4.67404189
 3.43555263 4.62910292 6.04322793 5.020859  ]
MIN: 3.4355526262927327
MAX: 6.043227929613549
MEAN: 4.762820694838392
MEDIAN: 4.7604804923817605
STANDARD DEVIATION: 0.676545830610117


**Dot Product**

In [23]:
f = np.array([1,2])
g = np.array([4,5])
np.dot(f, g)

14

**The Numpy matmul() function is used to return the matrix product of 2 arrays**

In [24]:
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
### 1*5+2*7 = 19
np.matmul(h, i)

array([[19, 22],
       [43, 50]])

**Inverse of a matrix**

In [25]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


**Determinant of a matrix**

In [27]:
n_array = np.array([[50, 29], [30, 44]])
print("Numpy Matrix is:",n_array)

det = np.linalg.det(n_array)
  
print("\nDeterminant of the matrix is:")
print(int(det))

Numpy Matrix is: [[50 29]
 [30 44]]

Determinant of the matrix is:
1330


**Rank of a matrix**

In [32]:
mx = np.array([[1,1,1],[0,1,2],[1,5,3]])
print(mx)

print("\nRank of the matrix is:")
np.linalg.matrix_rank(mx)

[[1 1 1]
 [0 1 2]
 [1 5 3]]

Rank of the matrix is:


3

**eigen values and eigen vectors**

In [33]:
example_matrix = np.array([
  [1,2,3,4],
  [5,6,7,8],
  [9,10,11,12],
  [13,14,15,16]
])
eigenvalues, eigenvectors = np.linalg.eig(example_matrix)
print(eigenvalues, eigenvectors)

[ 3.62093727e+01 -2.20937271e+00 -5.14138333e-16 -2.08943529e-15] [[-0.15115432 -0.72704996  0.01790738 -0.26832672]
 [-0.34923733 -0.28320876  0.38415354  0.71367217]
 [-0.54732033  0.16063243 -0.82202921 -0.62236419]
 [-0.74540333  0.60447363  0.41996829  0.17701873]]


**Diagonal of a matrix**

In [34]:
gfg = np.matrix('[6, 2; 3, 4]')       
diag = gfg.diagonal()  
print(diag)

[[6 4]]


**Transpose of a matrix**

In [35]:
gfg = np.matrix('[4, 1; 12, 3]')
trans = gfg.transpose()   
print(trans)

[[ 4 12]
 [ 1  3]]


**Trace of a matrix**

In [36]:
gfg = np.matrix('[4, 1; 12, 3]')              
tracem = gfg.trace()    
print(tracem)

[[7]]
